params:
  epochs: 3
  batch_size: 32
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plot_dir: plot
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: model.png

logs:
  log_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs